Bootstrap: docker
From: python:3.6-stretch

%help
    This container uses a Debian 9 "Stretch" foundation with python 3.6 to host a
    django-powered web site. This site is designed to provide documentation for
    users of the jjm* cluster it runs on.

    Typical usage:

        $ singularity run --bind /home/aa/jjmweb:/opt/jjmweb jjmweb.sif


%labels
    Maintainer Mike Schmidt
    Version 0.0.3

# Commands in setup are run on the host before running the container.
%setup

# Files from the host can be copied into the container
%files

# Environment variables for container run-time
%environment

# The main setup, happening inside the container
#    I'd like to use python 3's venv, but singularity doesn't seem to allow "source"ing
#    Running postgresql requires root, which defeats the singularity concept, so sqlite it is.
%post
    apt update \
    && apt upgrade -y \
    && apt install apache2 git sqlite python3-pip -y \
    && pip install --upgrade django
#    && rm -rf /opt/jjmweb \
#    && mkdir -p /opt/jjmweb \
#    && git clone https://github.com/mfschmidt/jjmweb.git /opt/jjmweb/


# Run this inside the container, after setup has occurred.
# %runscript

%startscript
    echo "____ running jjmweb ____"
    cd /opt/jjmweb/
    echo "    using python version $(python3 --version)"
    echo "    using pip version    $(python3 -m pip --version)"
    echo "    using django version $(python3 -m django --version)"
    python3 /opt/jjmweb/manage.py makemigrations
    python3 /opt/jjmweb/manage.py migrate
    python3 /opt/jjmweb/manage.py runserver 0:8080